version: "3.9"
services:
  trainer1:
    container_name: gateway-trainer1
    image: hmaid/hyperledger:dist-fed-gateway
    labels:
      service:
    volumes:
      - ${DIST_FED_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.chaincode.name=fedavg-chaincode"
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer1@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer1@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org1.organization=org1.example.com"
      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer1@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer1@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--trainer.org2.organization=org2.example.com"
      - "--server.port=6001"
    ports:
      - "6001:6001"
    network_mode: "host"
  trainer2:
    container_name: gateway-trainer2
    image: hmaid/hyperledger:dist-fed-gateway
    labels:
      service:
    volumes:
      - ${DIST_FED_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.chaincode.name=fedavg-chaincode"
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer2@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer2@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org1.organization=org1.example.com"
      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer2@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer2@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--trainer.org2.organization=org2.example.com"
      - "--server.port=6002"
    ports:
      - "6002:6002"
    network_mode: "host"
  trainer3:
    container_name: gateway-trainer3
    image: hmaid/hyperledger:dist-fed-gateway
    labels:
      service:
    volumes:
      - ${DIST_FED_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.chaincode.name=fedavg-chaincode"
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer3@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer3@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org1.organization=org1.example.com"
      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer3@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer3@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--trainer.org2.organization=org2.example.com"
      - "--server.port=6003"
    ports:
      - "6003:6003"
    network_mode: "host"
  trainer4:
    container_name: gateway-trainer4
    image: hmaid/hyperledger:dist-fed-gateway
    labels:
      service:
    volumes:
      - ${DIST_FED_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.chaincode.name=fedavg-chaincode"
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer4@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer4@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org1.organization=org1.example.com"
      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer4@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer4@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--trainer.org2.organization=org2.example.com"
      - "--server.port=6004"
    ports:
      - "6004:6004"
    network_mode: "host"