version: "3.9"
services:
  aggregator-org1:
    container_name: aggregator.org1.example.com
    image: dist-fed-gateway:latest
    labels:
      service: aggregator-dist-fed-gateway
    volumes:
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=aggregator"
      - "--others.cert.path=/credential/org1.example.com/users/Aggregator1@org1.example.com/msp/signcerts/cert.pem"
      - "--others.key-dir.path=/credential/org1.example.com/users/Aggregator1@org1.example.com/msp/keystore"
      - "--others.tls-cert.path=/credential/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"

  aggregator-org2:
    container_name: aggregator.org2.example.com
    image: dist-fed-gateway:latest
    labels:
      service: aggregator-dist-fed-gateway
    volumes:
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=aggregator"
      - "--others.cert.path=/credential/org2.example.com/users/Aggregator1@org2.example.com/msp/signcerts/cert.pem"
      - "--others.key-dir.path=/credential/org2.example.com/users/Aggregator1@org2.example.com/msp/keystore"
      - "--others.tls-cert.path=/credential/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"

  admin:
    container_name: admin.org2.example.com
    image: dist-fed-gateway:latest
    labels:
      service: admin-dist-fed-gateway
    volumes:
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=flAdmin"
      - "--others.cert.path=/credential/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem"
      - "--others.key-dir.path=/credential/org2.example.com/users/Admin@org2.example.com/msp/keystore"
      - "--others.tls-cert.path=/credential/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"

  leadAggregator:
    container_name: leadAggregator.org2.example.com
    image: dist-fed-gateway:latest
    labels:
      service: leadAggregator-dist-fed-gateway
    volumes:
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=leadAggregator"
      - "--others.cert.path=/credential/org2.example.com/users/LeadAggregator1@org2.example.com/msp/signcerts/cert.pem"
      - "--others.key-dir.path=/credential/org2.example.com/users/LeadAggregator1@org2.example.com/msp/keystore"
      - "--others.tls-cert.path=/credential/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"

  trainer01:
    container_name: trainer01.example.com
    image: dist-fed-gateway:latest
    labels:
      service: trainer-dist-fed-gateway
    volumes:
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/org1.example.com/users/Trainer1@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/org1.example.com/users/Trainer1@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org2.cert.path=/credential/org2.example.com/users/Trainer1@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/org2.example.com/users/Trainer1@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"

  trainer02:
    container_name: trainer02.example.com
    image: dist-fed-gateway:latest
    labels:
      service: trainer-dist-fed-gateway
    volumes:
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/org1.example.com/users/Trainer2@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/org1.example.com/users/Trainer2@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org2.cert.path=/credential/org2.example.com/users/Trainer2@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/org2.example.com/users/Trainer2@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"