version: "3.9"
services:
  trainer1:
    container_name: trainer1.gateway.com
    image: hmaid/hyperledger:dist-fed-gateway
    labels:
      service:
    volumes:
      - ${DIST_FED_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer1@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer1@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org1.organization=org1.example.com"
      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer1@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer1@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--trainer.org2.organization=org2.example.com"
      - "--server.port=6001"
    ports:
      - "6001:6001"
    network_mode: "host"
  trainer2:
    container_name: trainer2.example.com
    image: hmaid/hyperledger:dist-fed-gateway
    labels:
      service:
    volumes:
      - ${DIST_FED_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer2@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer2@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org1.organization=org1.example.com"
      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer2@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer2@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--trainer.org2.organization=org2.example.com"
      - "--server.port=6002"
    ports:
      - "6002:6002"
    network_mode: "host"
  trainer3:
    container_name: trainer3.example.com
    image: hmaid/hyperledger:dist-fed-gateway
    labels:
      service:
    volumes:
      - ${DIST_FED_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer3@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer3@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org1.organization=org1.example.com"
      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer3@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer3@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--trainer.org2.organization=org2.example.com"
      - "--server.port=6003"
    ports:
      - "6003:6003"
    network_mode: "host"
  trainer4:
    container_name: trainer4.example.com
    image: hmaid/hyperledger:dist-fed-gateway
    labels:
      service:
    volumes:
      - ${DIST_FED_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer4@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer4@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org1.organization=org1.example.com"
      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer4@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer4@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--trainer.org2.organization=org2.example.com"
      - "--server.port=6004"
    ports:
      - "6004:6004"
    network_mode: "host"
#  trainer5:
#    container_name: trainer5.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer5@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer5@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer5@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer5@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6005"
#    ports:
#      - "6005:6005"
#    network_mode: "host"
#  trainer6:
#    container_name: trainer6.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer6@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer6@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer6@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer6@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6006"
#    ports:
#      - "6006:6006"
#    network_mode: "host"
#  trainer7:
#    container_name: trainer7.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer7@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer7@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer7@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer7@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6007"
#    ports:
#      - "6007:6007"
#    network_mode: "host"
#  trainer8:
#    container_name: trainer8.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer8@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer8@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer8@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer8@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6008"
#    ports:
#      - "6008:6008"
#    network_mode: "host"
#  trainer9:
#    container_name: trainer9.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer9@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer9@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer9@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer9@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6009"
#    ports:
#      - "6009:6009"
#    network_mode: "host"
#  trainer10:
#    container_name: trainer10.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer10@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer10@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer10@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer10@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6010"
#    ports:
#      - "6010:6010"
#    network_mode: "host"
#  trainer11:
#    container_name: trainer11.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer11@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer11@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer11@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer11@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6011"
#    ports:
#      - "6011:6011"
#    network_mode: "host"
#  trainer12:
#    container_name: trainer12.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer12@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer12@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer12@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer12@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6012"
#    ports:
#      - "6012:6012"
#    network_mode: "host"
#  trainer13:
#    container_name: trainer13.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer13@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer13@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer13@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer13@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6013"
#    ports:
#      - "6013:6013"
#    network_mode: "host"
#  trainer14:
#    container_name: trainer14.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer14@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer14@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer14@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer14@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6014"
#    ports:
#      - "6014:6014"
#    network_mode: "host"
#  trainer15:
#    container_name: trainer15.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer15@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer15@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer15@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer15@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6015"
#    ports:
#      - "6015:6015"
#    network_mode: "host"
#  trainer16:
#    container_name: trainer16.example.com
#    image: hmaid/hyperledger:dist-fed-gateway
#    labels:
#      service:
#    volumes:
#      - ${DIST_FED_CREDENTIAL_HOME}:/credential
#    command:
#      - "--fl.role=trainer"
#      - "--trainer.org1.cert.path=/credential/peerOrganizations/org1.example.com/users/Trainer16@org1.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org1.key-dir.path=/credential/peerOrganizations/org1.example.com/users/Trainer16@org1.example.com/msp/keystore"
#      - "--trainer.org1.tls-cert.path=/credential/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
#      - "--trainer.org1.organization=org1.example.com"
#      - "--trainer.org2.cert.path=/credential/peerOrganizations/org2.example.com/users/Trainer16@org2.example.com/msp/signcerts/cert.pem"
#      - "--trainer.org2.key-dir.path=/credential/peerOrganizations/org2.example.com/users/Trainer16@org2.example.com/msp/keystore"
#      - "--trainer.org2.tls-cert.path=/credential/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
#      - "--trainer.org2.organization=org2.example.com"
#      - "--server.port=6016"
#    ports:
#      - "6016:6016"
#    network_mode: "host"
#
